fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.25.0"
    inifile:
      repo: "https://github.com/puppetlabs/puppetlabs-inifile"
      ref: "1.5.0"
    apache:
      repo: "https://github.com/puppetlabs/puppetlabs-apache"
      ref: "2.3.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat"
      ref: "4.1.1"
    php:
      repo: "https://github.com/thias/puppet-php"
      ref: "1.2.1"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
    composer:
      repo: "https://github.com/SugarFactory/puppet-composer"
      ref: "1.4.2"
    git:
      repo: "https://github.com/puppetlabs/puppetlabs-git"
      ref: "0.5.0"
    mysql:
      repo: "https://github.com/puppetlabs/puppetlabs-mysql"
      ref: "5.1.0"
    java:
      repo: "https://github.com/puppetlabs/puppetlabs-java"
      ref: "2.4.0"
    yum:
      repo: "https://github.com/voxpupuli/puppet-yum"
      ref: "v2.0.1"
    memcached:
      repo: "https://github.com/saz/puppet-memcached"
      ref: "v2.8.1"
    firewall:
      repo: "https://github.com/puppetlabs/puppetlabs-firewall"
      ref: "1.8.1"
    redis:
      repo: "https://github.com/arioch/puppet-redis"
      ref: "v3.2.0"
  forge_modules:
    elasticsearch:
      repo: elastic/elasticsearch
      ref: 5.4.3
    datacat:
      repo: richardc/datacat
      ref: 0.6.2
  symlinks:
    sugarcrmstack_ng: "#{source_dir}"
