fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.21.0"
    inifile:
      repo: "https://github.com/puppetlabs/puppetlabs-inifile"
      ref: "1.5.0"
    apache:
      repo: "https://github.com/puppetlabs/puppetlabs-apache"
      ref: "2.3.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat"
      ref: "4.1.1"
    php:
      repo: "https://github.com/thias/puppet-php"
      ref: "1.2.1"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
    composer: "https://github.com/tPl0ch/puppet-composer"
    git:    "https://github.com/puppetlabs/puppetlabs-git"
    mysql:
      repo: "https://github.com/puppetlabs/puppetlabs-mysql"
      ref: "5.1.0"
  symlinks:
    sugarcrmstack_ng: "#{source_dir}"
