fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile"
    apache: "https://github.com/puppetlabs/puppetlabs-apache"
  symlinks:
    sugarcrmstack_ng: "#{source_dir}"
