fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    puppetlabs-inifile: "https://github.com/puppetlabs/puppetlabs-inifile"
  symlinks:
    sugarcrmstack_ng: "#{source_dir}"
